#!/usr/bin/env node
/**
 * Bakes the solar system's calendar into `src/data/events.js`.
 *
 * Run with `npm run bake:events`. Committed, like everything else the app
 * reads — it makes no network requests, and this makes none either: every date
 * here is *searched for* using the app's own orbits, in `src/orbit/events.js`,
 * not copied from an almanac. That is the property worth having. Jump the clock
 * to an eclipse in this file and the eclipse is on screen, because the same
 * geometry decided both; a list transcribed from a published table would drift
 * away from the scene the moment either changed.
 *
 * ## Why bake at all
 *
 * Because the searches are sweeps. Finding every solar eclipse from 1800 to
 * 2050 evaluates the lunar series a third of a million times, which is a few
 * seconds — unremarkable in a build step and unacceptable in a page load, for a
 * panel most people will open once.
 *
 * Jupiter's shadow transits are deliberately *not* here. There are eight
 * hundred a year, so two centuries of them would be two hundred thousand rows
 * to save a search that takes milliseconds over the day actually on screen.
 * They are found live instead.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

import { PLANETS } from '../src/data/planetData.js'
import { EPOCH_RANGE } from '../src/data/orbitalElements.js'
import { bodyBasis, poleDirection, primeMeridianAt } from '../src/scene/pole.js'
import {
  conjunctions,
  greatestElongations,
  lunarEclipses,
  oppositions,
  ringPlaneCrossings,
  solarEclipses,
} from '../src/orbit/events.js'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src/data/events.js')

const FROM = EPOCH_RANGE.minJD
const TO = EPOCH_RANGE.maxJD

const elements = (id) => PLANETS.find((p) => p.id === id).elements
const earth = elements('earth')

/**
 * Planets that can be at opposition: the ones outside the Earth's orbit.
 *
 * Mercury and Venus are omitted because for them the event does not exist
 * rather than because it is uninteresting — they are never opposite the Sun.
 * They get greatest elongations instead, which is the corresponding thing an
 * inner planet does.
 */
const OUTER = ['mars', 'jupiter', 'saturn', 'uranus', 'neptune']
const INNER = ['mercury', 'venus']

function main() {
  const events = []
  const note = (label, rows) => {
    console.log(`[events] ${String(rows.length).padStart(5)}  ${label}`)
    events.push(...rows)
  }

  note(
    'solar eclipses',
    solarEclipses(FROM, TO, earth, {
      basis: bodyBasis('earth'),
      meridian: (jd) => primeMeridianAt('earth', jd),
    }),
  )

  note('lunar eclipses', lunarEclipses(FROM, TO, earth))

  for (const id of OUTER) {
    note(`${id} oppositions`, oppositions(elements(id), earth, FROM, TO).map((e) => ({ ...e, body: id })))
  }

  for (const id of INNER) {
    note(
      `${id} elongations`,
      greatestElongations(elements(id), earth, FROM, TO).map((e) => ({ ...e, body: id })),
    )
  }

  note(
    'Jupiter–Saturn conjunctions',
    conjunctions(elements('jupiter'), elements('saturn'), earth, FROM, TO).map((e) => ({
      ...e,
      body: 'jupiter',
      with: 'saturn',
    })),
  )

  note(
    'ring-plane crossings',
    ringPlaneCrossings(elements('saturn'), earth, poleDirection('saturn'), FROM, TO).map((e) => ({
      ...e,
      body: 'saturn',
    })),
  )

  events.sort((a, b) => a.jd - b.jd)

  const round = (n, places) => Number(n.toFixed(places))
  const rows = events
    .map((e) => {
      const fields = [`kind: '${e.kind}'`, `jd: ${round(e.jd, 5)}`]
      if (e.body) fields.push(`body: '${e.body}'`)
      if (e.with) fields.push(`with: '${e.with}'`)
      if (e.type) fields.push(`type: '${e.type}'`)
      if (e.side) fields.push(`side: '${e.side}'`)
      if (e.degrees !== undefined) fields.push(`degrees: ${round(e.degrees, 2)}`)
      if (e.umbralMagnitude !== undefined) {
        fields.push(`umbralMagnitude: ${round(e.umbralMagnitude, 3)}`)
      }
      if (e.latitude !== null && e.latitude !== undefined) {
        fields.push(`latitude: ${round(e.latitude, 2)}`, `longitude: ${round(e.longitude, 2)}`)
      }
      return `  { ${fields.join(', ')} },`
    })
    .join('\n')

  writeFileSync(
    OUT,
    `/**
 * Everything worth setting the clock to, ${new Date(
   (FROM - 2440587.5) * 86400000,
 ).getUTCFullYear()}–${new Date((TO - 2440587.5) * 86400000).getUTCFullYear()}.
 *
 * GENERATED by \`scripts/bake-events.mjs\` — do not hand-edit; rerun
 * \`npm run bake:events\` instead. Generated ${new Date().toISOString().slice(0, 10)}.
 *
 * Not transcribed from an almanac. Every date here was *found* by searching the
 * app's own orbits and orientations (\`src/orbit/events.js\`), which is what
 * makes the list and the scene incapable of disagreeing: set the clock to an
 * eclipse in this file and the eclipse is on screen, because one geometry
 * decided both.
 *
 * Sorted by date, across the window the orbital elements are valid for. Jupiter's
 * shadow transits are not here — there are eight hundred a year — and are found
 * live for whatever day is on screen.
 *
 * \`jd\` is a Julian Date in UT. Solar eclipse latitude and longitude are the
 * point of greatest eclipse, geodetic, degrees east.
 */

/**
 * @typedef {{
 *   kind: 'solar-eclipse' | 'lunar-eclipse' | 'opposition' | 'greatest-elongation'
 *       | 'conjunction' | 'ring-plane-crossing',
 *   jd: number,
 *   body?: string,
 *   with?: string,
 *   type?: string,
 *   side?: 'east' | 'west',
 *   degrees?: number,
 *   umbralMagnitude?: number,
 *   latitude?: number,
 *   longitude?: number,
 * }} SkyEvent
 */

/** @type {SkyEvent[]} */
export const EVENTS = [
${rows}
]
`,
  )

  console.log(`[events] ${events.length} total, wrote ${OUT}`)
}

main()
